# 서버 포트 설정
server:
  port: 18080

# DB 설정 (log 출력)
spring:
  datasource:
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/hr?
      # jdbc-url: jdbc:log4jdbc:mysql://10.200.12.77:3306/hr?
      username: hr
      password: spring
      connection-timeout: 10000
      validation-timeout: 10000
      connection-test-query: select 1 from dual

## DB 설정 (hikari CP 란? 검색해보기)
#spring:
#  datasource:
#    hikari:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      jdbc-url: jdbc:mysql://localhost:3306/hr?
#      username: hr
#      password: spring
#      connection-timeout: 10000
#      validation-timeout: 10000
#      connection-test-query: select 1 from dual

# 카멜 표기법 - 스네이크 표기법 매핑 설정
mybatis:
  configuration:
    map-underscore-to-camel-case: true
#  mapper-locations: mapper/**/sql-*.xml
