# 서버 포트 설정
server:
  port: 18080

# DB 설정 (log 출력)
spring:
  datasource:
    hikari:
      # driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/hr?
      # jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/hr?
      # jdbc-url: jdbc:log4jdbc:mysql://10.200.12.77:3306/hr?
      username: hr
      password: spring
      connection-timeout: 10000
      validation-timeout: 10000
      connection-test-query: select 1 from dual
  # JPA 설정
  jpa:
    hibernate:
      # 자동으로 처리할 DDL 종류 선택
      # ddl-auto: create
      ddl-auto: update

      # 하이버네이트의 새로운 ID 생성 옵션의 사용 여부 설정
      use-new-id-generator-mappings: false

    properties:
      hibernate:
        format_sql: true
        use_sql_commnets: true

    # 사용할 DB 선택
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

    # 테이블 생성과 스크립트를 자동으로 실행
    generate-ddl: false
    show-sql: true

  # 타임리프는 캐싱이 디폴트 값인데, 그러면 개발할 때 새로고침이 되지 않아서 개발할 때는 false로 설정해준다.
  thymeleaf:
    cache: false

  # 캐싱하는 데이터의 유지시간 설정
  web:
    resources:
      cache:
        period: 0

logging:
  level:
    org.hibernate.type.descriptor.sql: trace

## DB 설정 (hikari CP 란? 검색해보기)
#spring:
#  datasource:
#    hikari:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      jdbc-url: jdbc:mysql://localhost:3306/hr?
#      username: hr
#      password: spring
#      connection-timeout: 10000
#      validation-timeout: 10000
#      connection-test-query: select 1 from dual

# 카멜 표기법 - 스네이크 표기법 매핑 설정
mybatis:
  configuration:
    map-underscore-to-camel-case: true
#  mapper-locations: mapper/**/sql-*.xml

