server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234

  output:
    ansi:
      enabled: always

  jpa:
    hibernate:
      ddl-auto: create #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 572699404604-ikopqe30i0olusnivm11h7srilup029n.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          facebook:
            client-id: 416794553721632
            client-secret: f74fb92a6a97aa3793573f8bf86e662b
            scope:
              - email
              - public_profile
          naver:
            client-id: lb5ci_hiZtCPxjlMgHdO
            client-secret: CBfJAwoeKp
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            scope:
              - name
              - email

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response #회원정보를 json으로 받는데 response라는 키값으로 네이버가 리턴해줌
